version: '3.8'

services:
  twitch-youtube-stats:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: 'production'
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    networks:
      - default
